// flow-typed signature: 458dd077b3d28392bde0808bbb9746b7
// flow-typed version: <<STUB>>/iview_v^2.7.3/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'iview' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'iview/dist/iview' {
  declare module.exports: any;
}

declare module 'iview/dist/iview.min' {
  declare module.exports: any;
}

declare module 'iview/dist/locale/de-DE' {
  declare module.exports: any;
}

declare module 'iview/dist/locale/en-US' {
  declare module.exports: any;
}

declare module 'iview/dist/locale/es-ES' {
  declare module.exports: any;
}

declare module 'iview/dist/locale/fr-FR' {
  declare module.exports: any;
}

declare module 'iview/dist/locale/id-ID' {
  declare module.exports: any;
}

declare module 'iview/dist/locale/ja-JP' {
  declare module.exports: any;
}

declare module 'iview/dist/locale/ko-KR' {
  declare module.exports: any;
}

declare module 'iview/dist/locale/pt-BR' {
  declare module.exports: any;
}

declare module 'iview/dist/locale/pt-PT' {
  declare module.exports: any;
}

declare module 'iview/dist/locale/ru-RU' {
  declare module.exports: any;
}

declare module 'iview/dist/locale/sv-SE' {
  declare module.exports: any;
}

declare module 'iview/dist/locale/tr-TR' {
  declare module.exports: any;
}

declare module 'iview/dist/locale/uk-UA' {
  declare module.exports: any;
}

declare module 'iview/dist/locale/vi-VN' {
  declare module.exports: any;
}

declare module 'iview/dist/locale/zh-CN' {
  declare module.exports: any;
}

declare module 'iview/dist/locale/zh-TW' {
  declare module.exports: any;
}

declare module 'iview/src/components/affix/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/alert/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/auto-complete/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/avatar/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/back-top/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/badge/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/base/collapse-transition' {
  declare module.exports: any;
}

declare module 'iview/src/components/base/notification/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/base/popper' {
  declare module.exports: any;
}

declare module 'iview/src/components/base/render' {
  declare module.exports: any;
}

declare module 'iview/src/components/breadcrumb/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/button/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/card/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/carousel/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/cascader/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/checkbox/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/circle/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/collapse/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/color-picker/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/date-picker/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/date-picker/panel/mixin' {
  declare module.exports: any;
}

declare module 'iview/src/components/date-picker/picker/date-picker' {
  declare module.exports: any;
}

declare module 'iview/src/components/date-picker/picker/time-picker' {
  declare module.exports: any;
}

declare module 'iview/src/components/date-picker/time-mixins' {
  declare module.exports: any;
}

declare module 'iview/src/components/date-picker/util' {
  declare module.exports: any;
}

declare module 'iview/src/components/dropdown/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/form/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/grid/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/icon/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/input-number/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/input/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/loading-bar/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/loading-bar/loading-bar' {
  declare module.exports: any;
}

declare module 'iview/src/components/menu/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/message/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/modal/confirm' {
  declare module.exports: any;
}

declare module 'iview/src/components/modal/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/modal/mixins-scrollbar' {
  declare module.exports: any;
}

declare module 'iview/src/components/notice/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/page/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/poptip/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/progress/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/radio/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/rate/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/scroll/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/select/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/select/utils' {
  declare module.exports: any;
}

declare module 'iview/src/components/slider/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/spin/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/spin/spin' {
  declare module.exports: any;
}

declare module 'iview/src/components/steps/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/switch/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/table/expand' {
  declare module.exports: any;
}

declare module 'iview/src/components/table/export-csv' {
  declare module.exports: any;
}

declare module 'iview/src/components/table/header' {
  declare module.exports: any;
}

declare module 'iview/src/components/table/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/table/mixin' {
  declare module.exports: any;
}

declare module 'iview/src/components/tabs/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/tag/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/time-picker/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/timeline/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/tooltip/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/transfer/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/tree/index' {
  declare module.exports: any;
}

declare module 'iview/src/components/tree/render' {
  declare module.exports: any;
}

declare module 'iview/src/components/upload/ajax' {
  declare module.exports: any;
}

declare module 'iview/src/components/upload/index' {
  declare module.exports: any;
}

declare module 'iview/src/directives/clickoutside' {
  declare module.exports: any;
}

declare module 'iview/src/directives/transfer-dom' {
  declare module.exports: any;
}

declare module 'iview/src/index' {
  declare module.exports: any;
}

declare module 'iview/src/locale/format' {
  declare module.exports: any;
}

declare module 'iview/src/locale/index' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang/de-DE' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang/en-US' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang/es-ES' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang/fr-FR' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang/id-ID' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang/ja-JP' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang/ko-KR' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang/pt-BR' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang/pt-PT' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang/ru-RU' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang/sv-SE' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang/tr-TR' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang/uk-UA' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang/vi-VN' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang/zh-CN' {
  declare module.exports: any;
}

declare module 'iview/src/locale/lang/zh-TW' {
  declare module.exports: any;
}

declare module 'iview/src/mixins/emitter' {
  declare module.exports: any;
}

declare module 'iview/src/mixins/locale' {
  declare module.exports: any;
}

declare module 'iview/src/utils/assist' {
  declare module.exports: any;
}

declare module 'iview/src/utils/calcTextareaHeight' {
  declare module.exports: any;
}

declare module 'iview/src/utils/csv' {
  declare module.exports: any;
}

declare module 'iview/src/utils/date' {
  declare module.exports: any;
}

declare module 'iview/src/utils/dom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'iview/dist/iview.js' {
  declare module.exports: $Exports<'iview/dist/iview'>;
}
declare module 'iview/dist/iview.min.js' {
  declare module.exports: $Exports<'iview/dist/iview.min'>;
}
declare module 'iview/dist/locale/de-DE.js' {
  declare module.exports: $Exports<'iview/dist/locale/de-DE'>;
}
declare module 'iview/dist/locale/en-US.js' {
  declare module.exports: $Exports<'iview/dist/locale/en-US'>;
}
declare module 'iview/dist/locale/es-ES.js' {
  declare module.exports: $Exports<'iview/dist/locale/es-ES'>;
}
declare module 'iview/dist/locale/fr-FR.js' {
  declare module.exports: $Exports<'iview/dist/locale/fr-FR'>;
}
declare module 'iview/dist/locale/id-ID.js' {
  declare module.exports: $Exports<'iview/dist/locale/id-ID'>;
}
declare module 'iview/dist/locale/ja-JP.js' {
  declare module.exports: $Exports<'iview/dist/locale/ja-JP'>;
}
declare module 'iview/dist/locale/ko-KR.js' {
  declare module.exports: $Exports<'iview/dist/locale/ko-KR'>;
}
declare module 'iview/dist/locale/pt-BR.js' {
  declare module.exports: $Exports<'iview/dist/locale/pt-BR'>;
}
declare module 'iview/dist/locale/pt-PT.js' {
  declare module.exports: $Exports<'iview/dist/locale/pt-PT'>;
}
declare module 'iview/dist/locale/ru-RU.js' {
  declare module.exports: $Exports<'iview/dist/locale/ru-RU'>;
}
declare module 'iview/dist/locale/sv-SE.js' {
  declare module.exports: $Exports<'iview/dist/locale/sv-SE'>;
}
declare module 'iview/dist/locale/tr-TR.js' {
  declare module.exports: $Exports<'iview/dist/locale/tr-TR'>;
}
declare module 'iview/dist/locale/uk-UA.js' {
  declare module.exports: $Exports<'iview/dist/locale/uk-UA'>;
}
declare module 'iview/dist/locale/vi-VN.js' {
  declare module.exports: $Exports<'iview/dist/locale/vi-VN'>;
}
declare module 'iview/dist/locale/zh-CN.js' {
  declare module.exports: $Exports<'iview/dist/locale/zh-CN'>;
}
declare module 'iview/dist/locale/zh-TW.js' {
  declare module.exports: $Exports<'iview/dist/locale/zh-TW'>;
}
declare module 'iview/src/components/affix/index.js' {
  declare module.exports: $Exports<'iview/src/components/affix/index'>;
}
declare module 'iview/src/components/alert/index.js' {
  declare module.exports: $Exports<'iview/src/components/alert/index'>;
}
declare module 'iview/src/components/auto-complete/index.js' {
  declare module.exports: $Exports<'iview/src/components/auto-complete/index'>;
}
declare module 'iview/src/components/avatar/index.js' {
  declare module.exports: $Exports<'iview/src/components/avatar/index'>;
}
declare module 'iview/src/components/back-top/index.js' {
  declare module.exports: $Exports<'iview/src/components/back-top/index'>;
}
declare module 'iview/src/components/badge/index.js' {
  declare module.exports: $Exports<'iview/src/components/badge/index'>;
}
declare module 'iview/src/components/base/collapse-transition.js' {
  declare module.exports: $Exports<'iview/src/components/base/collapse-transition'>;
}
declare module 'iview/src/components/base/notification/index.js' {
  declare module.exports: $Exports<'iview/src/components/base/notification/index'>;
}
declare module 'iview/src/components/base/popper.js' {
  declare module.exports: $Exports<'iview/src/components/base/popper'>;
}
declare module 'iview/src/components/base/render.js' {
  declare module.exports: $Exports<'iview/src/components/base/render'>;
}
declare module 'iview/src/components/breadcrumb/index.js' {
  declare module.exports: $Exports<'iview/src/components/breadcrumb/index'>;
}
declare module 'iview/src/components/button/index.js' {
  declare module.exports: $Exports<'iview/src/components/button/index'>;
}
declare module 'iview/src/components/card/index.js' {
  declare module.exports: $Exports<'iview/src/components/card/index'>;
}
declare module 'iview/src/components/carousel/index.js' {
  declare module.exports: $Exports<'iview/src/components/carousel/index'>;
}
declare module 'iview/src/components/cascader/index.js' {
  declare module.exports: $Exports<'iview/src/components/cascader/index'>;
}
declare module 'iview/src/components/checkbox/index.js' {
  declare module.exports: $Exports<'iview/src/components/checkbox/index'>;
}
declare module 'iview/src/components/circle/index.js' {
  declare module.exports: $Exports<'iview/src/components/circle/index'>;
}
declare module 'iview/src/components/collapse/index.js' {
  declare module.exports: $Exports<'iview/src/components/collapse/index'>;
}
declare module 'iview/src/components/color-picker/index.js' {
  declare module.exports: $Exports<'iview/src/components/color-picker/index'>;
}
declare module 'iview/src/components/date-picker/index.js' {
  declare module.exports: $Exports<'iview/src/components/date-picker/index'>;
}
declare module 'iview/src/components/date-picker/panel/mixin.js' {
  declare module.exports: $Exports<'iview/src/components/date-picker/panel/mixin'>;
}
declare module 'iview/src/components/date-picker/picker/date-picker.js' {
  declare module.exports: $Exports<'iview/src/components/date-picker/picker/date-picker'>;
}
declare module 'iview/src/components/date-picker/picker/time-picker.js' {
  declare module.exports: $Exports<'iview/src/components/date-picker/picker/time-picker'>;
}
declare module 'iview/src/components/date-picker/time-mixins.js' {
  declare module.exports: $Exports<'iview/src/components/date-picker/time-mixins'>;
}
declare module 'iview/src/components/date-picker/util.js' {
  declare module.exports: $Exports<'iview/src/components/date-picker/util'>;
}
declare module 'iview/src/components/dropdown/index.js' {
  declare module.exports: $Exports<'iview/src/components/dropdown/index'>;
}
declare module 'iview/src/components/form/index.js' {
  declare module.exports: $Exports<'iview/src/components/form/index'>;
}
declare module 'iview/src/components/grid/index.js' {
  declare module.exports: $Exports<'iview/src/components/grid/index'>;
}
declare module 'iview/src/components/icon/index.js' {
  declare module.exports: $Exports<'iview/src/components/icon/index'>;
}
declare module 'iview/src/components/input-number/index.js' {
  declare module.exports: $Exports<'iview/src/components/input-number/index'>;
}
declare module 'iview/src/components/input/index.js' {
  declare module.exports: $Exports<'iview/src/components/input/index'>;
}
declare module 'iview/src/components/loading-bar/index.js' {
  declare module.exports: $Exports<'iview/src/components/loading-bar/index'>;
}
declare module 'iview/src/components/loading-bar/loading-bar.js' {
  declare module.exports: $Exports<'iview/src/components/loading-bar/loading-bar'>;
}
declare module 'iview/src/components/menu/index.js' {
  declare module.exports: $Exports<'iview/src/components/menu/index'>;
}
declare module 'iview/src/components/message/index.js' {
  declare module.exports: $Exports<'iview/src/components/message/index'>;
}
declare module 'iview/src/components/modal/confirm.js' {
  declare module.exports: $Exports<'iview/src/components/modal/confirm'>;
}
declare module 'iview/src/components/modal/index.js' {
  declare module.exports: $Exports<'iview/src/components/modal/index'>;
}
declare module 'iview/src/components/modal/mixins-scrollbar.js' {
  declare module.exports: $Exports<'iview/src/components/modal/mixins-scrollbar'>;
}
declare module 'iview/src/components/notice/index.js' {
  declare module.exports: $Exports<'iview/src/components/notice/index'>;
}
declare module 'iview/src/components/page/index.js' {
  declare module.exports: $Exports<'iview/src/components/page/index'>;
}
declare module 'iview/src/components/poptip/index.js' {
  declare module.exports: $Exports<'iview/src/components/poptip/index'>;
}
declare module 'iview/src/components/progress/index.js' {
  declare module.exports: $Exports<'iview/src/components/progress/index'>;
}
declare module 'iview/src/components/radio/index.js' {
  declare module.exports: $Exports<'iview/src/components/radio/index'>;
}
declare module 'iview/src/components/rate/index.js' {
  declare module.exports: $Exports<'iview/src/components/rate/index'>;
}
declare module 'iview/src/components/scroll/index.js' {
  declare module.exports: $Exports<'iview/src/components/scroll/index'>;
}
declare module 'iview/src/components/select/index.js' {
  declare module.exports: $Exports<'iview/src/components/select/index'>;
}
declare module 'iview/src/components/select/utils.js' {
  declare module.exports: $Exports<'iview/src/components/select/utils'>;
}
declare module 'iview/src/components/slider/index.js' {
  declare module.exports: $Exports<'iview/src/components/slider/index'>;
}
declare module 'iview/src/components/spin/index.js' {
  declare module.exports: $Exports<'iview/src/components/spin/index'>;
}
declare module 'iview/src/components/spin/spin.js' {
  declare module.exports: $Exports<'iview/src/components/spin/spin'>;
}
declare module 'iview/src/components/steps/index.js' {
  declare module.exports: $Exports<'iview/src/components/steps/index'>;
}
declare module 'iview/src/components/switch/index.js' {
  declare module.exports: $Exports<'iview/src/components/switch/index'>;
}
declare module 'iview/src/components/table/expand.js' {
  declare module.exports: $Exports<'iview/src/components/table/expand'>;
}
declare module 'iview/src/components/table/export-csv.js' {
  declare module.exports: $Exports<'iview/src/components/table/export-csv'>;
}
declare module 'iview/src/components/table/header.js' {
  declare module.exports: $Exports<'iview/src/components/table/header'>;
}
declare module 'iview/src/components/table/index.js' {
  declare module.exports: $Exports<'iview/src/components/table/index'>;
}
declare module 'iview/src/components/table/mixin.js' {
  declare module.exports: $Exports<'iview/src/components/table/mixin'>;
}
declare module 'iview/src/components/tabs/index.js' {
  declare module.exports: $Exports<'iview/src/components/tabs/index'>;
}
declare module 'iview/src/components/tag/index.js' {
  declare module.exports: $Exports<'iview/src/components/tag/index'>;
}
declare module 'iview/src/components/time-picker/index.js' {
  declare module.exports: $Exports<'iview/src/components/time-picker/index'>;
}
declare module 'iview/src/components/timeline/index.js' {
  declare module.exports: $Exports<'iview/src/components/timeline/index'>;
}
declare module 'iview/src/components/tooltip/index.js' {
  declare module.exports: $Exports<'iview/src/components/tooltip/index'>;
}
declare module 'iview/src/components/transfer/index.js' {
  declare module.exports: $Exports<'iview/src/components/transfer/index'>;
}
declare module 'iview/src/components/tree/index.js' {
  declare module.exports: $Exports<'iview/src/components/tree/index'>;
}
declare module 'iview/src/components/tree/render.js' {
  declare module.exports: $Exports<'iview/src/components/tree/render'>;
}
declare module 'iview/src/components/upload/ajax.js' {
  declare module.exports: $Exports<'iview/src/components/upload/ajax'>;
}
declare module 'iview/src/components/upload/index.js' {
  declare module.exports: $Exports<'iview/src/components/upload/index'>;
}
declare module 'iview/src/directives/clickoutside.js' {
  declare module.exports: $Exports<'iview/src/directives/clickoutside'>;
}
declare module 'iview/src/directives/transfer-dom.js' {
  declare module.exports: $Exports<'iview/src/directives/transfer-dom'>;
}
declare module 'iview/src/index.js' {
  declare module.exports: $Exports<'iview/src/index'>;
}
declare module 'iview/src/locale/format.js' {
  declare module.exports: $Exports<'iview/src/locale/format'>;
}
declare module 'iview/src/locale/index.js' {
  declare module.exports: $Exports<'iview/src/locale/index'>;
}
declare module 'iview/src/locale/lang.js' {
  declare module.exports: $Exports<'iview/src/locale/lang'>;
}
declare module 'iview/src/locale/lang/de-DE.js' {
  declare module.exports: $Exports<'iview/src/locale/lang/de-DE'>;
}
declare module 'iview/src/locale/lang/en-US.js' {
  declare module.exports: $Exports<'iview/src/locale/lang/en-US'>;
}
declare module 'iview/src/locale/lang/es-ES.js' {
  declare module.exports: $Exports<'iview/src/locale/lang/es-ES'>;
}
declare module 'iview/src/locale/lang/fr-FR.js' {
  declare module.exports: $Exports<'iview/src/locale/lang/fr-FR'>;
}
declare module 'iview/src/locale/lang/id-ID.js' {
  declare module.exports: $Exports<'iview/src/locale/lang/id-ID'>;
}
declare module 'iview/src/locale/lang/ja-JP.js' {
  declare module.exports: $Exports<'iview/src/locale/lang/ja-JP'>;
}
declare module 'iview/src/locale/lang/ko-KR.js' {
  declare module.exports: $Exports<'iview/src/locale/lang/ko-KR'>;
}
declare module 'iview/src/locale/lang/pt-BR.js' {
  declare module.exports: $Exports<'iview/src/locale/lang/pt-BR'>;
}
declare module 'iview/src/locale/lang/pt-PT.js' {
  declare module.exports: $Exports<'iview/src/locale/lang/pt-PT'>;
}
declare module 'iview/src/locale/lang/ru-RU.js' {
  declare module.exports: $Exports<'iview/src/locale/lang/ru-RU'>;
}
declare module 'iview/src/locale/lang/sv-SE.js' {
  declare module.exports: $Exports<'iview/src/locale/lang/sv-SE'>;
}
declare module 'iview/src/locale/lang/tr-TR.js' {
  declare module.exports: $Exports<'iview/src/locale/lang/tr-TR'>;
}
declare module 'iview/src/locale/lang/uk-UA.js' {
  declare module.exports: $Exports<'iview/src/locale/lang/uk-UA'>;
}
declare module 'iview/src/locale/lang/vi-VN.js' {
  declare module.exports: $Exports<'iview/src/locale/lang/vi-VN'>;
}
declare module 'iview/src/locale/lang/zh-CN.js' {
  declare module.exports: $Exports<'iview/src/locale/lang/zh-CN'>;
}
declare module 'iview/src/locale/lang/zh-TW.js' {
  declare module.exports: $Exports<'iview/src/locale/lang/zh-TW'>;
}
declare module 'iview/src/mixins/emitter.js' {
  declare module.exports: $Exports<'iview/src/mixins/emitter'>;
}
declare module 'iview/src/mixins/locale.js' {
  declare module.exports: $Exports<'iview/src/mixins/locale'>;
}
declare module 'iview/src/utils/assist.js' {
  declare module.exports: $Exports<'iview/src/utils/assist'>;
}
declare module 'iview/src/utils/calcTextareaHeight.js' {
  declare module.exports: $Exports<'iview/src/utils/calcTextareaHeight'>;
}
declare module 'iview/src/utils/csv.js' {
  declare module.exports: $Exports<'iview/src/utils/csv'>;
}
declare module 'iview/src/utils/date.js' {
  declare module.exports: $Exports<'iview/src/utils/date'>;
}
declare module 'iview/src/utils/dom.js' {
  declare module.exports: $Exports<'iview/src/utils/dom'>;
}
