// flow-typed signature: d07c570d2e353b4ad6a5d81081610d26
// flow-typed version: <<STUB>>/portfinder_v^1.0.13/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'portfinder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'portfinder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'portfinder/lib/portfinder' {
  declare module.exports: any;
}

// Filename aliases
declare module 'portfinder/lib/portfinder.js' {
  declare module.exports: $Exports<'portfinder/lib/portfinder'>;
}
