// flow-typed signature: 2da758cb578d52a3f26207db35e4c6ad
// flow-typed version: <<STUB>>/postcss-filter-gradient_v^1.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-filter-gradient'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-filter-gradient' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-filter-gradient/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'postcss-filter-gradient/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-filter-gradient/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'postcss-filter-gradient/coverage/lcov-report/prettify'>;
}
declare module 'postcss-filter-gradient/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'postcss-filter-gradient/coverage/lcov-report/sorter'>;
}
declare module 'postcss-filter-gradient/index' {
  declare module.exports: $Exports<'postcss-filter-gradient'>;
}
declare module 'postcss-filter-gradient/index.js' {
  declare module.exports: $Exports<'postcss-filter-gradient'>;
}
