// flow-typed signature: 8a1ec7eb6b4091ebdbe89a5a7cf461a7
// flow-typed version: <<STUB>>/vue-class-component_v^6.1.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-class-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-class-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-class-component/dist/vue-class-component.common' {
  declare module.exports: any;
}

declare module 'vue-class-component/dist/vue-class-component' {
  declare module.exports: any;
}

declare module 'vue-class-component/dist/vue-class-component.min' {
  declare module.exports: any;
}

declare module 'vue-class-component/lib/component' {
  declare module.exports: any;
}

declare module 'vue-class-component/lib/data' {
  declare module.exports: any;
}

declare module 'vue-class-component/lib/declarations' {
  declare module.exports: any;
}

declare module 'vue-class-component/lib/index' {
  declare module.exports: any;
}

declare module 'vue-class-component/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-class-component/dist/vue-class-component.common.js' {
  declare module.exports: $Exports<'vue-class-component/dist/vue-class-component.common'>;
}
declare module 'vue-class-component/dist/vue-class-component.js' {
  declare module.exports: $Exports<'vue-class-component/dist/vue-class-component'>;
}
declare module 'vue-class-component/dist/vue-class-component.min.js' {
  declare module.exports: $Exports<'vue-class-component/dist/vue-class-component.min'>;
}
declare module 'vue-class-component/lib/component.js' {
  declare module.exports: $Exports<'vue-class-component/lib/component'>;
}
declare module 'vue-class-component/lib/data.js' {
  declare module.exports: $Exports<'vue-class-component/lib/data'>;
}
declare module 'vue-class-component/lib/declarations.js' {
  declare module.exports: $Exports<'vue-class-component/lib/declarations'>;
}
declare module 'vue-class-component/lib/index.js' {
  declare module.exports: $Exports<'vue-class-component/lib/index'>;
}
declare module 'vue-class-component/lib/util.js' {
  declare module.exports: $Exports<'vue-class-component/lib/util'>;
}
